# Generated by Django 3.1.2 on 2020-10-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0004_auto_20201023_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='countrycode',
            field=models.CharField(default='+91', max_length=20, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
