# Generated by Django 3.1.2 on 2020-10-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0005_auto_20201023_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='countrycode',
            field=models.CharField(max_length=20, verbose_name='Country Code'),
        ),
    ]
