# Generated by Django 3.1.2 on 2020-10-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0006_auto_20201023_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(blank=True, default='0', verbose_name='Phone Number'),
        ),
    ]
