# Generated by Django 3.1.2 on 2020-10-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0007_auto_20201023_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedatabase',
            name='Cast',
        ),
        migrations.RemoveField(
            model_name='moviedatabase',
            name='Director',
        ),
        migrations.AddField(
            model_name='moviedatabase',
            name='cast',
            field=models.CharField(default=None, max_length=100, verbose_name='Cast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedatabase',
            name='director',
            field=models.CharField(default=None, max_length=100, verbose_name='Director'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedatabase',
            name='playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookedseats',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='moviedatabase',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nowplaying',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showing', to='movietime.moviedatabase', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='nowplaying',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Playing Number'),
        ),
    ]
