# Generated by Django 3.1.2 on 2020-10-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0014_auto_20201024_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BookingQuota',
            field=models.IntegerField(default=5, verbose_name='Booking Quota'),
        ),
    ]
