# Generated by Django 3.1.2 on 2020-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0015_user_bookingquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DailyLimit', models.IntegerField(default=25)),
                ('SlotLimit', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='countrycode',
            field=models.CharField(default='0', max_length=20, verbose_name='Country Code'),
        ),
    ]
