# Generated by Django 3.1.2 on 2020-10-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0016_auto_20201024_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TheatreSettings',
        ),
    ]
