# Generated by Django 3.1.2 on 2020-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0017_delete_theatresettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.BigIntegerField(blank=True, default='0', verbose_name='Phone Number'),
        ),
    ]
